### ISSUE TITLE
The latest version, 1.17.17, has an extra dot before the version number

### ISSUE THREAD

**Issue by JerryFan626** [yizhoumo/setup-ossutil#40]
<img width="1369" alt="image" src="https://github.com/yizhoumo/setup-ossutil/assets/7688101/aad8d842-74a4-4238-856d-f25cd692f77f">

**Comment by fxzxmicah** [comment]
https://github.com/aliyun/ossutil/issues/229
😂

**Comment by fxzxmicah** [comment]
Fixed by aliyun developer.
