### ISSUE TITLE
你好，由于github升级 导致无法使用了 麻烦修复下 谢谢！

### ISSUE THREAD

**Issue by hiair2323** [yizhoumo/setup-ossutil#5]
Run yizhoumo/setup-ossutil@v1.0.1
Downloading ossutil from: http://gosspublic.alicdn.com/ossutil/1.6.11/ossutil64
Error: Unable to process command '::add-path::/opt/hostedtoolcache/ossutil/1.6.11/x64' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

用来用去还是你的最好用！

**Comment by yizhoumo** [comment]
Hi hiair2323. Thanks for your notice and sorry for the delay.
This issue should be fixed by 3f8b34f4cda971d6917ee66f769fc3eb1996c2a3 now.

**Comment by yizhoumo** [comment]
A newer version is released.
https://github.com/yizhoumo/setup-ossutil/releases/tag/v1.0.2

Thank you again for your remiding.
